### ISSUE TITLE
KISS FC Settings

### ISSUE THREAD

**Issue by 19Gerhard85** [ImpulseRC/OSD#1]
@awolf78 
May you can post / describe the settings for the KISS FC if everything is connected to ImpulseOSD?

**Comment by awolf78** [comment]
Defaults should work, make sure Serial config is configured to OSD. You can optionally set the VTX to Dummy VTX if you want ImpulseOSD to synchronize with the KISS FC. Then you can use LUA to change channels as well.

**Comment by 19Gerhard85** [comment]
Thanks! Can I keep the VTX setting "SmartAudio" or should it be Dummy VTX?

**Comment by awolf78** [comment]
I recommend using Dummy VTX
