### ISSUE TITLE
VTx power on a switch?

### ISSUE THREAD

**Issue by olivier0253** [ImpulseRC/OSD#10]
Hello,
First of all, thanks for your work!

Then..  I would like to manage vtx power with a switch, (25/600mW on aux channel) independently of arming status. What i have to do on the osd?
 
Thank you in advance,

Olivier

**Comment by awolf78** [comment]
For now this is tied to the arm switch. We are going to implement this feature in a future FW upgrade.

**Comment by olivier0253** [comment]
ok, thank you for the answer.
so, i'm waiting for the next release :)

**Comment by awolf78** [comment]
Implemented
