### ISSUE TITLE
No Audio just weird clicking Sounds

### ISSUE THREAD

**Issue by Richygoat** [ImpulseRC/OSD#12]
Hello,
today i replaced the Steele PDB against the Wolf PDB an i don't have audio anymore.
vTX is the ImmersionRC Tramp.

When i disconnect the Audio wire from the PDB there is silence in the headphone. Connect it back only loads clicking sounds.

Newest firmware ist flashed.

Everything else is working fine.

regards

**Comment by awolf78** [comment]
Did you solder the microphone on the WolfPDB? Can you show some pictures how you have soldered everything?

**Comment by Richygoat** [comment]
Yes microphone is soldered on. And here are some pictures.

**Comment by Richygoat** [comment]
![img_3988](https://user-images.githubusercontent.com/36879085/45589040-11e2c880-b91f-11e8-95cd-7400584a82fa.jpg)
![img_3993](https://user-images.githubusercontent.com/36879085/45589041-11e2c880-b91f-11e8-9668-3ead146e2f2b.jpg)
![img_3987](https://user-images.githubusercontent.com/36879085/45589042-11e2c880-b91f-11e8-931a-c3eaba2df6c1.jpg)
![img_3991](https://user-images.githubusercontent.com/36879085/45589043-11e2c880-b91f-11e8-89e7-bbe56cf698a4.jpg)
![img_3990](https://user-images.githubusercontent.com/36879085/45589044-11e2c880-b91f-11e8-9a95-214781c2f36f.jpg)
![img_3989](https://user-images.githubusercontent.com/36879085/45589045-11e2c880-b91f-11e8-9a54-4c1090a970a0.jpg)

**Comment by awolf78** [comment]
Most probably a defective microphone. Please contact your dealer for a replacement. Sorry this happened to you.

**Comment by Richygoat** [comment]
That was my thought too. But when i desolder the microphone this noise sound is still there.

**Comment by Richygoat** [comment]
i could try to solder the microphone from my Steele PDB in the Wolf PDB when they're the same.

**Comment by Richygoat** [comment]
I have tried the working microphone from the Steele PDB on the Wolf PDB. Still don’t working. After putting it back on the Steele PDB Everything working fine again.

**Comment by awolf78** [comment]
Sorry this happened to you. Please contact your dealer for a replacement.

**Comment by Richygoat** [comment]
Yes. I tried 2 TrampHV. Both are working fine on the Steele PDB.

**Comment by awolf78** [comment]
OK, then you need to have your board replaced unfortunately.
