### ISSUE TITLE
No red status light/GUI does not recognize device

### ISSUE THREAD

**Issue by turbokc** [ImpulseRC/OSD#15]
During an update of the Wolf PDB, my battery had a short. Now, there is no red status light on the PDB (green one is on). No OSD visible. When I connect the USB, the GUI does not recognize the device and remains in searching mode.  Fried?

**Comment by awolf78** [comment]
1. Temporarily bridge SDA and GND (e.g. with tweezers)
2. Plug in a Lipo. Remove bridge between SDA and GND. Red light should be blinking.
3. Connect with GUI

**Comment by turbokc** [comment]
Many thanks!! Works great again.
