### ISSUE TITLE
Micro Swift 3 Serial Communication Wolf PDB and Kiss v2 

### ISSUE THREAD

**Issue by Ayougo** [ImpulseRC/OSD#17]
Wolf PDB with latest firmeware
Kiss v2 with RC36I firmware
Micro Swift 3 connect via TX/RX  (TX from Swift to RX on Wolf PDB, RX from Swift to TX on Wolf PDB)

Issue: No Internal OSD menu on new swift 3 micro with serial camera control 

Yaw left, toward bottom or zero throttle, hold for several seconds, enter menu, select "camera control", Yaw Left  == No Internal OSD menu

**Comment by mkct93** [comment]
Same here friend. 😐

**Comment by awolf78** [comment]
Go to SETUP->CAMERA CONTROL and change CAMERA CONTROL to SERIAL.

**Comment by awolf78** [comment]
Cam RX connected to PDB Camera TX?

**Comment by mkct93** [comment]
Yes. I swapped it around both ways in case the camera wasn’t labeled correctly. Still nothing. I’ll try another camera tonight that I know works with the serial connection and post the results. Also I am using the rev1 pdb.

**Comment by mkct93** [comment]
Fantastic! I’ll give it a go tonight. Pdb is awesome by the way. Great piece of kit. 👍🏻

**Comment by mkct93** [comment]
That was it. Thank you so much.
