### ISSUE TITLE
OSD stopped working

### ISSUE THREAD

**Issue by Anckero** [ImpulseRC/OSD#18]
My OSD is not showing up anymore with my WolfPDB. I don't get values nor ImpulseRC boot logo.
The green LED is on but the red one is not flashing as it should.
The PDB is not connecting to my PC.

I searched online and found on RCgroups a guy who stopped a firmware update by mistake and he had the exact same issues. So even if my problem is not coming form a bad firmware update I followed the steps.
I temporarily bridged SDA and GND then connected the USB. This trick worked, the red light was flashing and the PDB was recognized by my PC. As an update was available I flashed it and it went well.

But then I unplugged the XT60 and USB and this issue is still there on my next attempt to connect the XT60, no red LED flashing.

I'm using a KISS FC v1.03 FW1.3-RC36i

**Comment by awolf78** [comment]
Do the SDA and GND trick again, but this time select Full Chip Erase in the GUI before you flash.

**Comment by Anckero** [comment]
Fantastic! All is back to normal.
Thank you very much awolf78! 😃

**Comment by Oberlurch3000** [comment]
Please could you tell me how this trick works? I've the same problem since today. Just no OSD in the FPV screen and the red LED is off. WIndows tells me that the device has not been recognized. Why is this happening? I did no changes to it in the last few weeks.

**Comment by Anckero** [comment]
Hi @Oberlurch3000 
Here is the RCGroups thread I first found the instructions: https://www.rcgroups.com/forums/showthread.php?2806289-KISS-OSD-Firmware-new-versions-posted-here/page126#post40795311

Just follow the instructions as per Awolf78's comment on RCGroups and you should be fine. If the problem persists you may have to do the "Full Chip Erase" thing in the GUI as Awolf78 told me to do on this GitHub thread. :)

**Comment by Oberlurch3000** [comment]
Wow thanks! I like things that work ;). But very strange that it happend anyway.

**Comment by Anckero** [comment]
Yeah it's pretty strange. Mine stopped working like yours, without any reason. But it has been working great since this fix so you should be fine too. :)

**Comment by Brightontillifly** [comment]
> Do the SDA and GND trick again, but this time select Full Chip Erase in the GUI before you flash.

this totally worked for me nice one Wolf!

**Comment by Ub6ib9** [comment]
Awesome so there is hope. Out of nowhere the osd quit working and gps wasn't getting a lock. I'm hoping this process will work. I'll chime back in after trying.
