### ISSUE TITLE
Wrong Wiring Diagram for KISSFC V1 - KISSFC-1.3-RC36c and SmartAudio

### ISSUE THREAD

**Issue by Hawxxer** [ImpulseRC/OSD#19]
On the Wiring Diagram one should connect the smartaudio connection to the TX Pad, but on KISS Controller V1 and newer firmware (think 1.3RC10) it needs to be connected to RX.

See comment on 1.3RC36h release:
https://github.com/flyduino/kissfc-firmware/releases/tag/1.3RC36h

**Comment by Hawxxer** [comment]
Yes I do and I tried to connect it to TX on the PDB, but than the Taranis LUA Script didn't work. After connecting it to RX on the PDB it worked.

**Comment by awolf78** [comment]
Read here:
https://github.com/ImpulseRC/OSD/wiki/Firmware:-Video-Transmitter#lua-support

**Comment by Hawxxer** [comment]
I read it, yes. Tried again connecting Smartaudio to TX on PDB, now its working...
