### ISSUE TITLE
Problem GPS Bn180

### ISSUE THREAD

**Issue by Mick51** [ImpulseRC/OSD#21]
Hello I'm having a problem with the pdb Wolf with a GPS bn 180, everything is well connected but the GPS is not détecté ! No GPS detection by the Wolf and the kiss, the GPS is connected to the Wolf pdb. I do not understand anything! It would seem that the data does not go up while GPS works on another fc. Compatibility problems between the GPS and the Wolf is possible ?
Or a firmware problem of the Wolf pdb, I'm on the latest firmware on the Wolf as on the kiss !

**Comment by awolf78** [comment]
Must be connected wrong, I used the same GPS for development. Please double check your wiring.
