### ISSUE TITLE
New pinouts vor VTX and cam on rev2

### ISSUE THREAD

**Issue by benazet** [ImpulseRC/OSD#22]
Hello I just found out that the pinouts have changed for VTX and cam, and it is not mentionned in the hardware section of the github.
As it seems to be the official user guide for the Wolf, i think it would deserve a warning or an update.
I found the info on a product info page of a merchant site : https://www.drone-fpv-racer.com/pdb-osd-wolf-reverb-impulserc-3407.html 
I think this picture has its place on the hardware page.
Although it was annoying, luckily nothing was broken but i guess this is a tribute to the quality of the product. 
Now i switched the wires it works great.

**Comment by awolf78** [comment]
I literally just updated the hardware section a few minutes ago showing the new pinout. Sorry for the inconvenience.

**Comment by benazet** [comment]
Great job !

I guess i have to blame the merchant site for delvering to quickly then ! I ordered it monday and began to build wednesday.

**Comment by benazet** [comment]
The link of your picture is broken.

**Comment by awolf78** [comment]
Fixed

**Comment by benazet** [comment]
;)
