### ISSUE TITLE
Steele PDB only sometimes audio

### ISSUE THREAD

**Issue by Dragon-FPV** [ImpulseRC/OSD#28]
Hello,

unfortunately I have no sound any more (it worked fine). I don't know when it started and how (perhaps crash), but now I only have sound for some time when I hit something (e.g. a branch) during the flight without crashing. But just for a while, than the sound is gone again.
It seems like a loose connection, but where?

I tried everthing, all wires are ok and correct soldered, I replaced them ... but at the end the same issue. I also didn't find out what I can do by myself to simulate what happens due hitting something.

I guess microphone is working as there is sound again and again. And it's fixed on the PDB.

What else can I try / could be the reason?

thx and greetz

(KISS FC V2, KISS ESC 32A, Steele PDB, TBS Unify Pro V3, 6S)

**Comment by rauar** [comment]
I think this is the wrong repository. Steele PDB should be here: https://github.com/awolf78/KISS_OSD
