### ISSUE TITLE
 Rssi %

### ISSUE THREAD

**Issue by Bandi017** [ImpulseRC/OSD#29]
this is not an Issue but more of a question for which i have not yet found an answer: 
i have a full kiss setup along side this PDB for OSD. but until now i have not found a setting for the RSSI to show it in percentage instead of bars...Personally i find the bars not enough to correctly judge if i am still on the safe side or not.

**Comment by awolf78** [comment]
If you have the Windows GUI, click on Icons and turn the RSSI icon off.
Otherwise yaw to the left for more than 5 seconds and go to SETUP->BASIC SETUP->ICONS and turn the RSSI icon off there.

**Comment by Bandi017** [comment]
i think i need to change my glasses asap...thanks....
