### ISSUE TITLE
Wolf PDB won't connect to Impulse OSD app

### ISSUE THREAD

**Issue by briankalski** [ImpulseRC/OSD#31]
I can't get the Impulse OSD app to see my Wolf PDB.  I did flash the Steele PDB firmware to the board which I am assuming is the wrong firmware.  Is there somewhere I can get the Wolf PDB firmware?

**Comment by awolf78** [comment]
How did you flash the SteelePDB firmware on the WolfPDB?

**Comment by briankalski** [comment]
Using Xloader.  It was my first quad.

**Comment by awolf78** [comment]
XLoader cannot flash the WolfPDB. Does the WolfPDB work (red LED is blinking and shows OSD)?

**Comment by briankalski** [comment]
Everything works fine.  The OSD works.  I just can't connect to ImpulseOSD to change my OSD settings.  I ran the driver fixer and that won't connect either.  I tried a Mobula7 and it worked with that.

**Comment by briankalski** [comment]
The last time I changed the OSD settings I had to unplug port 2 and flash the Steele PDB config tool.

**Comment by awolf78** [comment]
The ImpulseOSD GUI does not work with the SteelePDB. You will have to flash the config tool if you want to make changes to your OSD.
