### ISSUE TITLE
OSD will not centered

### ISSUE THREAD

**Issue by carloscampos775** [ImpulseRC/OSD#33]
Can't get APEX OSD to center vertically using 57.15. Can't move items to the top of the screen. Using RunCam Swift Mini 2 with TBS Unify Pro 5v

**Comment by sblakemore** [comment]
What display device are you using, goggles or screen of some kind? Different displays often show different portions of the image.

Can you please get some DVR footage so we can see how things look?

Might also be worth doing a flash with full chip erase enabled to make sure the config is clean.

**Comment by carloscampos775** [comment]
I'm using Fatshark HDO’s with RapidFire. I'm not having this problem with the Wolf Reverb PDB only the Apex OSD. It's also cutting off the back/exit item in the OSD menus. I will try the full chip erase and update the issue.

![ImpluseOSD_1](https://user-images.githubusercontent.com/25696022/66712975-a31aad80-ed72-11e9-94f5-40d515d4da02.png)

**Comment by carloscampos775** [comment]
This is after a full chip erase. Still not working correctly. I have also tried another camera but the problem still persists.

Default OSD layout after full chip erase:
![IMPLUSE_OSD_RESET](https://user-images.githubusercontent.com/25696022/66716352-ceb18e00-ed9a-11e9-9bc2-7e7a817ce5fe.png)
 
This is what I need to do in the configurator to get the OSD items to show on screen:
![IMPLUSE_OSD_LOOK](https://user-images.githubusercontent.com/25696022/66716374-27812680-ed9b-11e9-97f4-5bfcd8410136.JPG)

**Comment by Herbiefpv** [comment]
I am also having this exact issue. I can adjust the osd side to side but it will not let me move it up. I can see something barley at the bottom. I also tried re flashing but no luck.

**Comment by Herbiefpv** [comment]
Awesome thanks Sean!

**Comment by sblakemore** [comment]
Thanks again for the feedback, I believe I just fixed this. We should have a new release soon for you to try!

**Comment by sblakemore** [comment]
If you would like to test a Beta release with the fix I can enable your OSD for Beta updates. All you need to do is connect the OSD to the GUI and then press Ctrl+Shift+D and you will get a popup with your hardware ID. Then just hit Ctrl+C to copy the ID and paste it in here and I'll set it up for you!

**Comment by carloscampos775** [comment]
I would like to try the beta. Here is my hardware ID

Device ID: 0011 1025 4847 750A 2037 7341

**Comment by awolf78** [comment]
Please download the beta GUI from here:
[http://osd-storage.impulserc.com/deploy-beta/setup.exe](url)

That should offer you V59.15. Let us know how it goes.

**Comment by carloscampos775** [comment]
Looks much better. If you could get it to center just a little high that would be perfect.

Default look after flashing
### 
![ImpluseOSD_5](https://user-images.githubusercontent.com/25696022/66830816-60003c00-ef24-11e9-9c90-bce0da59b775.png)

**Comment by Herbiefpv** [comment]
O was i suppose to use a certain gui? I just used the latest one i got the
other day but it will centered mine lol

**Comment by carloscampos775** [comment]
I was able to center the OSD by using the Advanced options. However, I have gotten a flickering OSD twice now since updating  

Video of issue:
https://www.dropbox.com/s/xo40cu8j2zytp4t/PICT0051.AVI?dl=0

**Comment by sblakemore** [comment]
@Herbiefpv Beta GUI not a requirement for this update, you will be fine :)

@carloscampos775 Vertical jumping like that is to do with the sync level your camera is putting out. You should be able to fix it by adjusting the sync detection level using the camera settings dialog in the GUI. There is a slider in there you can move up or down, will take some trial and error to find a value that works for you. Looks like it's about on the edge so probably will only take a small movement up or down to be stable.

**Comment by carloscampos775** [comment]
@sblakemore I found the camera sync setting. I think i'm good. Thanks for your help ;)
