### ISSUE TITLE
Apex OSD no image no OSD

### ISSUE THREAD

**Issue by jesbombero** [ImpulseRC/OSD#35]
The Apex OSD board I received when connected to camera and vtx, nothing is displayed in goggles. Channel is broadcasting but just grey screen, voltages from regulator are all correct and led lights show it is communicating with KISS V2 FC????

**Comment by sblakemore** [comment]
Hi mate, this tracker is for issues to do with the ImpulseOSD firmware itself. For more general support requests or hardware problems can you please contact ImpulseRC support and they should be able to help with troubleshooting!

**Comment by jesbombero** [comment]
Ok sure, thanks

Justin Smith
