### ISSUE TITLE
Unify can not be configured

### ISSUE THREAD

**Issue by warp2** [ImpulseRC/OSD#37]
Hi I can't configure my unify pro32 over OSD nor LUA script on the Taranis. Video is working with all other stuff (GPS, Battery...)
I have connected:
- 7-26V In (unify) to HV Power at the Wolf PDB
- GND to GND
- Video (unify) to Video Out at the Wolf PDB
- CRSF RX (unify) to VTX TX at the Wolf PDB
Any suggestion?
Or can I connect the CRSF RX to the Kiss as normally when having a setup without Wolf PDB?
Thanks a lot

**Comment by awolf78** [comment]
Connect your Unify Pro32 to the TBS Agent and switch CRSF RX to SmartAudio.

**Comment by warp2** [comment]
this did the trick, thanks for the tip
