### ISSUE TITLE
Led Strip Not Changing Color

### ISSUE THREAD

**Issue by dsalexander99** [ImpulseRC/OSD#38]
I installed the led strips provided with the apex frame and they only blink red. I cannot change the color through the apex osd.

**Comment by awolf78** [comment]
Please read [https://github.com/ImpulseRC/OSD/wiki/Firmware:-LED-strip](url)

**Comment by dsalexander99** [comment]
I’ve already read the info provided. I go thru the osd menu to led strip and try to change mode and color but nothing happens. It’s just stuck blinking red in the “knight” mode.

**Comment by awolf78** [comment]
Can you post a DVR what you are doing?

**Comment by dsalexander99** [comment]
https://www.dropbox.com/s/7y3exxyjwp1n5ge/Video%20Nov%2014%2C%208%2012%2021%20AM.mp4?dl=0

**Comment by dsalexander99** [comment]
That’s a link to the video. Bare with me, I couldn’t get my dvr to record.

**Comment by awolf78VDRS** [comment]
LED #1 is the one on the regulator board. LED #2-#7 are the ones that are in Knight mode. You need to select those and change the function/color for them

**Comment by awolf78** [comment]
LED #1 is the one on the regulator board. LED #2-#7 are the ones that are in Knight mode. You need to select those and change the function/color for them

**Comment by dsalexander99** [comment]
Thanks, I figured I was doing something wrong just didn’t know what.
