### ISSUE TITLE
Won’t connect to configurator

### ISSUE THREAD

**Issue by mReXiTuS** [ImpulseRC/OSD#39]
Hi Alex,

I was updating my wolf pdb with latest firmware and battery slipped out during process. Now I can’t connect to Impulse OSD configurator, it’s not recognized. 

I tried shorting SDA and GND pins as you suggested in different threads, but it doesn’t work and I still have only green led.

However, I was able to enter DFU mode and DfuseDemo app can recognize DFU device, but I would need firmware file so I can re-flash it. Can you please send me something? Or is there any other way how to make it work? Afaik STM MCUs cannot be bricked and there is always way to reflash it either over DFU or worst case with STLink. 

Thanks in advace.

**Comment by sblakemore** [comment]
Hi,

Sadly we can't give you a copy of our bootloader to flash over DFU, I genuinely wish we could but we would have our code stolen if we didn't protect it.

If you can't flash it by shorting SDA and GND then you can ship it back to ImpulseRC and we will try to recover it for you. If you want to go that route please just open a support ticket with ImpulseRC.

Cheers
