### ISSUE TITLE
gps coordinates

### ISSUE THREAD

**Issue by fnsweet** [ImpulseRC/OSD#4]
Are the GPS coordinates passed over telemetry using KISS FCv2 and crossfire?  I have tried to discover new senors in the taranis but no gps sensors found.

**Comment by awolf78** [comment]
With latest KISS FC FW, available through latest KISS GUI here:
https://github.com/flyduino/kissfc-chrome-gui/releases

**Comment by fnsweet** [comment]
I am currently running KISSFCV2F7-1.3RC36c

**Comment by awolf78** [comment]
Does the GPS work on your WolfPDB? Do you see coordinates in the OSD? They are only displayed once the home position has been initialized

**Comment by fnsweet** [comment]
The coordinates do work in the OSD

**Comment by awolf78** [comment]
Did you upgrade the FW on the WolfPDB to the latest?

**Comment by fnsweet** [comment]
The fw is the latest stable version of 17.8

**Comment by awolf78** [comment]
UPDATE: Talked to KISS devs, it looks like the GPS support did not make it in the latest release - but will confirm tomorrow.

**Comment by fnsweet** [comment]
Thank you, will wait for the next release :-)

**Comment by awolf78** [comment]
Implemented in latest KISS FC release
