### ISSUE TITLE
Wolf V3 Pinout

### ISSUE THREAD

**Issue by aijayadams** [ImpulseRC/OSD#43]
This wiki is linked from the product page as official documentation for the Wolf v3, but doesn't contain board diagram / pin out information about that product revision. Could we get permission to include (or link so) something like https://blog.seidel-philipp.de/impulserc-wolf-pdb-v3-fettec-kiss-fc-anschlussplan-wiringplan/

**Comment by rauar** [comment]
I think a pin out diagram with descriptions of what the pins do would be better than Phillip's diagram. The latter highlights just a few specific use-cases and does so by drawing connections to other (specific) hardware. For example the vtx audio and mic pads and the cam control pad definitely lack documentation.

**Comment by awolf78** [comment]
Done:
[Wolf V3 in Wiki](https://github.com/ImpulseRC/OSD/wiki/Hardware:-Wolf-PDB-V3)
