### ISSUE TITLE
Wolf PDB v3 OSD Disappearing 

### ISSUE THREAD

**Issue by FlamingComet** [ImpulseRC/OSD#44]
I have the new Wolf PDB v3 and sometimes when I plug up my quad the OSD will come up but before I can take off the OSD disappears and I am just left with a timer. I then unplug and plug the battery in and it stays up.

**Comment by awolf78** [comment]
What camera do you use? Do you have a DVR?

**Comment by FlamingComet** [comment]
It is the RunCam Swift 2. I do not have the camera controls wired up to the PDB. I dont have anything to record DVR.

**Comment by awolf78** [comment]
I would still increase the camera sync level to 200.

**Comment by FlamingComet** [comment]
Ok thanks, I will give that a try.

**Comment by FlamingComet** [comment]
I changed the camera sync level to 200 and have not a single problem since. Thank you for the help!
