### ISSUE TITLE
LED copy works but not saved via OSD

### ISSUE THREAD

**Issue by rauar** [ImpulseRC/OSD#49]
Just noticed that I can copy one LED to a range of other LEDs and see the effect correctly applied. However on reboot then (power cycle) the copied values are lost and I see the LEDs as configured before the changes.

On the other hand when I set the values manually by not using the copy operation the LED settings survive the reboot.

**Comment by awolf78** [comment]
Thanks for reporting this bug, will be fixed in next release.
