### ISSUE TITLE
Dead wolf pdb osd?

### ISSUE THREAD

**Issue by charalambos12** [ImpulseRC/OSD#53]
Hello, im having a black screen after a crash. After a lot of checks, the vtx is working fine and the cam is dead. When i plug a new cam i continue to have black screen so i think its an internal video failure. Using a multimeter, the current output of vtx and cam pads is normal and the gnds are ok, so only the video pad remains. What do you think?
Setup:
Kiss v2
Wolf pdb v1
Unify pro hv

**Comment by awolf78** [comment]
Even when the cam is dead or not connected, you should still see the OSD on a V1/V2. Is the red LED still blinking?

**Comment by sblakemore** [comment]
@charalambos12 This issue tracker is really only meant for firmware related discussions. If you have a hardware issue can you please contact ImpulseRC support and they will help you troubleshoot.

**Comment by charalambos12** [comment]
Sure, sorry for that. Didnt know

On 18 Feb 2020, at 06:11, sblakemore <notifications@github.com> wrote:

﻿

@charalambos12<https://github.com/charalambos12> This issue tracker is really only meant for firmware related discussions. If you have a hardware issue can you please contact ImpulseRC support and they will help you troubleshoot.
