### ISSUE TITLE
Wolf PDB v3 with Kiss FC v1 - no connection to FC

### ISSUE THREAD

**Issue by Tiptock** [ImpulseRC/OSD#54]
I already Updated the Wolf v3 to the newest stable firmware. It still says "no connection to fc 0"
I just tried out a little bit more. Now my RunCam 2 swift just transfers black image and then there is "no signal" on my goggles. Did I break anything completly by building? Or is this a Software sided problem.
@awolf78 
Thanks in advance guys.

**Comment by awolf78** [comment]
This is not a software related issue, please contact ImpulseRC support on their website to resolve this.
