### ISSUE TITLE
Missing release notes / changelog

### ISSUE THREAD

**Issue by rauar** [ImpulseRC/OSD#55]
Just wanted to check back here in the repo to find out if newer releases of the firmware are available and if so what was added/changed. But it seems there's nothing available here.

I guess the only option is to actually hook up the Wolf PDB to the laptop and start the ImpulseRC app (which is quite an act for simply checking if a newer firmware release is available).

**Comment by awolf78** [comment]
I don't agree it is that much of an act to hook up the PDB and start the app (but that's opinions and matter of taste).
I do agree that there is no cumulative changelog anywhere and it is not very convenient in the app to browse through all the change logs. Will add them in the release section here.

**Comment by awolf78** [comment]
Release notes are [here](https://github.com/ImpulseRC/OSD/releases)

**Comment by rauar** [comment]
Thanks a lot for adding.

If you have no quad and/or a working laptop with the app installed and/or a usb cable at your hands (e.g. on the road, at work etc.) it is really difficult ;)

Again thanks !

PS: perhaps a release date makes sense as well 😇 at least for upcoming releases.

**Comment by awolf78** [comment]
GitHub will take care of the release date automatically for future releases :)
