### ISSUE TITLE
Brokenlink for Betaflight and ImpulseOSD page

### ISSUE THREAD

**Issue by udyux** [ImpulseRC/OSD#58]
Most likely in response to #57 the "Betaflight - WolfPDB" page was updated and renamed. The links at the top of the main page and the sidebar links are still pointing to
`https://github.com/ImpulseRC/OSD/wiki/Betaflight-WolfPDB:-Please-read!!!` instead of `https://github.com/ImpulseRC/OSD/wiki/Betaflight-and-ImpulseOSD:-Please-read!!!`, the latter only being accessible the "pages" dropdown nav.

GitHub just ends up bringing you back to the main page with some edit-permissions warning.

**Comment by awolf78** [comment]
Fixed
