### ISSUE TITLE
Please add "strobe" mode to LED action to comply with new EU/EEA regulation

### ISSUE THREAD

**Issue by oyvindp** [ImpulseRC/OSD#59]
There is new regulation for drone classifications, types of operation etc. for drones in the European Union (EU) and European Economic Area (EEA), coming to effect now, with final deadline for implementation in law across the region this summer.

According to the new regulation, to be able to fly FPV, quads needs to be equipped with white lights at a certain strength, that flash a minimum number of times per minutes. This can easily be achieved with sufficient number of leds connected to the OSD board. however the mode for "strobe" doesnt exist. Sparkle would be the next best (and coolest) thing, but that wont comply with the new regulation.

This is what the Norwegian Civil Aviation Authority writes on the matter:
>Section 59. Mandatory lights
For all BLOS flying, the aircraft shall be fitted out with white low-intensity lights with a light intensity of at least 10 candela, where flashes are produced by rotating lights (strobe lights) at a rate of at least 20 flashes per minute.

Source: https://luftfartstilsynet.no/en/drones/commercial-use-of-drones/about-dronesrpas/regulations-of-drones/

The need for strobe lights is mandatory for all FPV flying ("BLOS" (Beyond Visual Line of Sight)) regardless if its commercial or hobby/recreational flying (even though the URL implies commercial operations).

Please consider adding a "strobe" mode in the LED settings, with minimum 20 flashes per minute. :)

**Comment by awolf78** [comment]
Next version will have a strobe mode around 25 flashes per minute. "Strobe" is a bit confusing (users would expect a higher frequency), I will call it "Blink".
