### ISSUE TITLE
Wrong ESC Speed/Temp with BLHeli_32?

### ISSUE THREAD

**Issue by milindur** [ImpulseRC/OSD#6]
Hello,

today I installed the Wolf PDB in my Reverb together with the Bardwell F4 AIO FC (Betaflight v3.4.1). The ESCs are Airbot Wraith32 v2 with latest BLHeli_32 v32.52 firmware (beta). The ESC current seems to be okay, but temperature and RPM are way off.

![img_0763](https://user-images.githubusercontent.com/227603/43989989-00ee7dc0-9d55-11e8-90b4-0bef70d733ae.jpg)

This sounds similar to this issue: bitdump/BLHeli#318

**Comment by awolf78** [comment]
Yes, this is a known issue. I have done lots of improvements for BF support lately and I'm overdue for a new release. Need to do some more testing which is challenging with all this rain we have here...

**Comment by milindur** [comment]
Thanks! Good to know about the fix, so it is not an issue of my build. If I can help testing anything regarding BF, please let me know.

**Comment by awolf78** [comment]
Fixed in V19.8
