### ISSUE TITLE
MacOS - firmware flashing - app unavailable

### ISSUE THREAD

**Issue by udyux** [ImpulseRC/OSD#60]
I'm having the scene cycling issue described in #34 on my RunCam Swift JohnnyFPV and intend to flash the latest firmware on my Apex OSD to solve this.

Trouble is when I follow [the app store link](https://itunes.apple.com/us/app/impulseosd/id1416313087) on the [ImpulseRC downloads page](https://impulserc.com/pages/downloads) I get a message saying "This app is currently not available in your country or region". For reference, I live in Canada.

For now I can set "CAMERA SYNC" level to `200` which should solve the issue, but are there any other methods for flashing?

*Edit:* just noting that the link provided on the [Config Tool: Install wiki page's Mac section](https://github.com/ImpulseRC/OSD/wiki/Config-Tool:-Install#mac) seems to point to the same link with the same result.

**Comment by awolf78** [comment]
The Swift JohnnyFPV needs a cam sync of 200.
We will look into the app store issue.

**Comment by xayahrakan** [comment]
I have the same issue in germany. When clicking https://apps.apple.com/us/app/impulseosd/id1416313087 App Store opens but shows: "This app is currently not available in your country or region".

**Comment by udyux** [comment]
Closing as the problem seems to be resolved for me. Was able to install!
