### ISSUE TITLE
Forgotten settings after a random number of packs

### ISSUE THREAD

**Issue by marcelkk** [ImpulseRC/OSD#61]
I have the third Wolf PDB V3 now with the same issue: After a random number of power cycles (10-50 flights for example) the PDB starts and all settings are at the default values (OSD elements, VTX settings, battery...).
From this point the PDB only saves settings temporarily. I’m able to save settings at the begin of a pack, after power cycle it one time the settings are forgotten.

To Flash it with the GUI and „full chip erase“ will bring it back into normal working mode. But even then its a number of random packs again until the issue will start again.

6S Setup with 4x 470uF Low ESR Elkos (really well soldered and built well considered!)
Flyduino KISS V2 
Flyduino ESC 32 A
Runcam Phoenix 2/Caddx Ratel (same problem with both cams)
Unify Pro V3 5V

**Comment by awolf78** [comment]
At this point I need:

- Detailed pictures how everything is wired up on your entire build (Not only the OSD related stuff)
- Backup of your settings from the Windows ImpulseOSD GUI.

**Comment by marcelkk** [comment]
![Wiring Reverb](https://user-images.githubusercontent.com/65137502/81564370-eafcc400-9397-11ea-8510-9fbb95e5844e.jpeg)
I hope the picture explains everything you need!?
Tried cam sync between -100 and +100, best at mean Value=0!
[2020-05-11_14-34-51_ImpulseOSD.faa.zip](https://github.com/ImpulseRC/OSD/files/4609711/2020-05-11_14-34-51_ImpulseOSD.faa.zip)

**Comment by Vegetabondfpv** [comment]
Hello, I have the same problem as marcelkk.

My 4s lipo setup

Wolf Pdb v3 (softmount) 
Fettec F7 FC
4x 25A Kiss esc
TBS unify pro hv VTX
RunCam sparrow 2 pro
Crossfire nano Rx

![IMG_20200511_162949](https://user-images.githubusercontent.com/65175752/81573974-7d579480-93a5-11ea-8d4c-e93f02c413b5.jpg)

**Comment by awolf78** [comment]
Does this also happen when you flash V68.20?

**Comment by marcelkk** [comment]
Yes, with both (V68.20 and V75.21)

**Comment by awolf78** [comment]
Can you send me a backup of your KISS FC config also please?

**Comment by marcelkk** [comment]
[kissfc-backup.txt](https://github.com/ImpulseRC/OSD/files/4616416/kissfc-backup.txt)
Sure!

**Comment by awolf78** [comment]
You can try a beta if you want which will hopefully fix this issue (hard to find since I cannot reproduce it). Please post your MCU ID here so I can add you to the beta program. To get your MCU ID, press Ctrl+Shift+D in the Windows GUI and paste the contents of the Window that pops up here.
If you are on a MAC, go in the OSD menu (yaw left for more than 3 seconds) and go to SETUP->RESET. On the bottom of the Reset menu you will see a very long number - I need that including all the zeroes.

**Comment by marcelkk** [comment]
I want to try everything that could fix it!

Device ID: 0047 7045 5547 7514 2032 2352

Is there any indication of what might be causing the problem? Please let me know if you're allowed to :-) For me it is also frustrating not to know whats wrong with my PDB/setup/whatever...
![Wolf MCU ID](https://user-images.githubusercontent.com/65137502/81991144-dd1d9c00-9640-11ea-8d00-eeffacaf4c55.png)

**Comment by awolf78** [comment]
Please download and install the beta GUI from [here](http://osd-storage.impulserc.com/deploy-beta/setup.exe)

I added your MCU ID. Let me know how it goes.

**Comment by marcelkk** [comment]
I flashed V79.23 and try it. I let you know if there are any problems. Thank you for the support!

**Comment by awolf78** [comment]
I haven't heard anything so I am assuming this is fixed and I can close it?

**Comment by marcelkk** [comment]
I would wait a few packs/flights more to be shure it’s fixed. In the past the failure happened after 4 weeks per example, so let’s wait a few weeks to be shure its really fixed. Until now everything is great 👌

**Comment by marcelkk** [comment]
I think it’s time to say the issue is fixed!
No problem since flashing V79.23!
Thank you for the great support!
