### ISSUE TITLE
Issue with TBS GPS and apex OSD.

### ISSUE THREAD

**Issue by bosbefok** [ImpulseRC/OSD#69]
I'm having an issue getting a connection with a TBS GPS. The GPS tx/rx pads are wired to the apex osd rx/tx pads. On power on the GPS receives power however the GPS related osd elements just continually flash. I've tried outside under clear skies for about 10minutes. I'm not seeing any updates at all, no satellites found, no coords etc.

Do you have any suggestions?

**Comment by awolf78** [comment]
May have to wait longer than 10 minutes for first lock. Does the sat count go up in the OSD or does it stay at 0?

**Comment by bosbefok** [comment]
It stays at 0. All osd GPS elements just flash continuously. Is there any way to get more info about whats going on?

**Comment by awolf78** [comment]
Not really, but if it doesn't acquire any satellites for 10 minutes outside that is not a good sign. May want to try a different GPS module

**Comment by bosbefok** [comment]
Tried with a brainfpv gps module and everything worked immediately. This indicates an issue with the TBS gps.
