### ISSUE TITLE
Many serial communication errors occurred

### ISSUE THREAD

**Issue by ebeez** [ImpulseRC/OSD#78]
Hi,
I am getting this error once I connect tot he FETtec configurator and click on the telemetry button settings button. I can connect fine and see all 4 ESC's in the overview. I plug in the micro USB cable first, open the configurator, plug in the Lipo and then hit connect. All fine at that point. As soon as I click the telemetry or setting button i get a series of beeps and then the error in the subject line

**Comment by awolf78** [comment]
Sorry, but this issue has nothing to do with ImpulseOSD related hardware. Please contact FETTEC support about the issue with the ESCs you are having.
