### ISSUE TITLE
Wrong voltage after update on 19.8 - stable

### ISSUE THREAD

**Issue by surfinggiant** [ImpulseRC/OSD#8]
After updating the Wolf PDB to 19.8 the OSD shows the wrong lipo voltage. I tried to downgrade but the voltage is still wrong.

The PDB is connected to a kiss fc V1.

**Comment by awolf78** [comment]
How much is it off?
Can you check what is set for the voltage correction in the battery menu?

**Comment by surfinggiant** [comment]
thats sound crazy, but on 3s lipo with 11,35 volts, osd shows 21,3 volts. on a 4s lipo with 15,25 volts the osd shows 25,2 volts. instead of 2 at the beginning it has to be a 1

**Comment by awolf78** [comment]
What happens if you move around the voltage in the OSD with the GUI? If the voltage overlaps with something it can have that effect...

**Comment by awolf78** [comment]
Time to contact support:
https://impulserc.com/pages/contact-us
