### ISSUE TITLE
Firmware flash failed "critical error"

### ISSUE THREAD

**Issue by TheTomJon** [ImpulseRC/OSD#81]
Building 3 inch build with KISS CompactCTRL CC AIO. Got "FC not Recognized Error". Went to update firmware of ApexOSD, started fine and started updating but got critical error. VTX no longer send video through OSD, Computer no longer recognizes OSD, and OSD GUI won't recognize it either. Tried emergency flash I found here... no luck... computer still doesnt recognize. No red LED, just green LED next to USB port.

One issue lead to another :( What can I do?

**Comment by sblakemore** [comment]
Sounds like a hardware issue. This issue tracker is for firmware related discussions only. Please contact the support department of the place you purchased from, hopefully they can help you further.
