### ISSUE TITLE
Font not changeable + missing signs

### ISSUE THREAD

**Issue by blackdrone911** [ImpulseRC/OSD#86]
Hey!
1. Why it’s not possible to change the OSD font? It’s shown in the GUI but in the goggles  it’s still the basic font. 
2. Also there are some signs missing. Instead of °C you can see there 2 big black bars. The same you can find in the statistics when disarming the quad. 
How I can fix that?
Full chip erase I tried 2 times without any solution for both problems.
![6A25C951-268C-4838-8861-9890A4D9D7BD](https://user-images.githubusercontent.com/59781523/108637059-3c8ac100-7489-11eb-97e0-2e389ee7d4db.jpeg)
![C324F4DE-4C29-49CB-B115-89D05874ADDB](https://user-images.githubusercontent.com/59781523/108637060-3dbbee00-7489-11eb-904a-76da88d0baa0.jpeg)

**Comment by awolf78** [comment]
Please flash again with Full Chip Erase. IMPORTANT: After you have flashed (and clicked OK to go back to OSD setup screen in the GUI), keep the Lipo plugged in for another 20-30 seconds. During that time it flashes the font again. Then the characters you are missing will be shown correctly.
Font: Can you show me how you are doing that? In a video?

**Comment by blackdrone911** [comment]
ok now it looks much better! Now there is only 1 black bar in the picture but we are making progress!
Attached is the video, but I think you can’t do something wrong there. Finally this is working too!
![B1F96CC2-CE53-475A-8C90-E44B86E8D033](https://user-images.githubusercontent.com/59781523/108750679-98b11c00-7541-11eb-93c8-596c75e8cc12.jpeg)


![D0783819-41F3-4E7D-B548-99DBD8F785B4](https://user-images.githubusercontent.com/59781523/108749775-81bdfa00-7540-11eb-82ea-c4cec77e496b.jpeg)
![Uploading DDFE0278-88D8-4AB9-A083-AA970B3A41DE.jpeg…]()


https://user-images.githubusercontent.com/59781523/108750224-10cb1200-7541-11eb-8a44-e82aad8875a9.MP4

**Comment by awolf78** [comment]
OK, looks like the font changes accordingly. 
The black bar in front of the (MCU) temperature should also have been fixed by the full chip erase method - you can try again and wait after it restarted. There should be a small square box with white legs that looks like a MCU when the font is correctly loaded.

**Comment by blackdrone911** [comment]
I tried 3-4 times after I got tired. Tomorrow I’ll try to flash the old software than the newest one, maybe this helps?

**Comment by blackdrone911** [comment]
So, now the PDB is blocked after several full chip erases. What now?
![769F5A28-B0A8-414B-B70B-BA7341DDFEA7](https://user-images.githubusercontent.com/59781523/108898534-98835000-7617-11eb-8574-ee28720ec32d.jpeg)

**Comment by awolf78** [comment]
Post your Device ID here - or if you do not feel comfortable doing that open a support ticket with ImpulseRC. They will unblock it for you.

**Comment by blackdrone911** [comment]
Ok, here is the image with the ID.
Is there another method the get the bugs out instead of full chip erase?

Edit: ID image deleted

**Comment by awolf78** [comment]
I removed your device from the blacklist.
I am guessing it is only that one character next to the temperature that has that issue? The only way to fix that is with a full chip erase, but since you have done this multiple times already and it did not help I can only assume that this part of the flash on you chip is defective. You can present this case to your dealer, but it is up to them how to handle this.

**Comment by blackdrone911** [comment]
Nah, it’s nearly new :)
So, now it’s done! Seems that the downgrade helped me out! Everything looks as it should! Great, I am fine again! Many thanks for the support!

![6392E1EF-BF39-410C-B4A1-B5D08B230C90](https://user-images.githubusercontent.com/59781523/109049275-5ff77b00-76d8-11eb-984a-0ca4a9a8ea9c.jpeg)
