### ISSUE TITLE
Altitude in statistic are relative to sea level

### ISSUE THREAD

**Issue by slackista** [ImpulseRC/OSD#87]
I have BMP388 and GPS with V90.27 v2 board. In post flight statistic max an min altitude are probably relative to sea level.  Values are to big. In previous versions of firmware problem did not occur.

**Comment by awolf78** [comment]
I have uploaded V91.27 that should fix this issue and #88. I cannot test it myself unfortunately, please let me know if this fixes it.

**Comment by slackista** [comment]
Thank you for fast fix. Tested changes today. Statistic are fine now. New issues found:
* GPS ~7/10 power ups, no GPS via crsf telemetry and no beep from buzzer(distinctive gps beep). OSD was OK. 
* For the first time was very hard to get fix. After half hour, lots of unplugged battery finally GPS got fix. Probably because no setup init command to gps was send. 
* ~1/10 power ups no GPS on OSD.
Previous firmware also had issues with random lack of gps crsf telemetry feed. But initialization problem was more noticeable now.

**Comment by slackista** [comment]
Thank you for fast fix. Tested today, and worked fine.
One more thing, in crsf telemetry feed altitude is relative to sea level ;)

**Comment by awolf78** [comment]
OK, please flash V91.27 again (I replaced the binary with one that fixes this).

**Comment by slackista** [comment]
Fixed. thanks!
