### ISSUE TITLE
Smartaudio does not respond

### ISSUE THREAD

**Issue by iblisfpv** [ImpulseRC/OSD#96]
I just bought an Apex Mr Steele frame kit:
Kiss fc v2,kiss 25a 4 un 1, tbs unify pro 5g8 v3, tbs crossfire nano rx version v6.10 and Impulserc OSD with its filter.

The question that I think I have all well soldered and it turns out that the Smartaudio does not answer, I try to change the channel of the vtx in the osd and nothing, of the gui kiss and nothing….

Any idea what it could be????

Thanks.

**Comment by sblakemore** [comment]
Hi, your best bet is to open a support ticket by emailing support@impulserc.com
Thanks!

**Comment by iblisfpv** [comment]
Hello, you're right I'll do that.

Thanks
