### ISSUE TITLE
MSP Display Port

### ISSUE THREAD

**Issue by SiCFPV** [ImpulseRC/OSD#97]
Hello,

The new FETTec Alpha Firmware is using MSP Display Port for the OSD. Is it possible to implement MSP Display Port on the ImpulseRC Apex OSD? I'm getting "FC Not Detected".

Thank you!

**Comment by sblakemore** [comment]
Hi mate, sorry but unfortunately since we can no longer produce ImpulseOSD hardware due to chip shortages the firmware is not in active development and we won't be adding any new features going forward.
